---
abstract: 'Ensure no pending commits on a remote branch before release'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.4008
  Test::More: 1.001002
configure_requires:
  Module::Build: 0.4008
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Git-Remote-Check
provides:
  Dist::Zilla::Plugin::Git::Remote::Check:
    file: lib/Dist/Zilla/Plugin/Git/Remote/Check.pm
    version: v0.1.3
  Dist::Zilla::Plugin::Git::Remote::Check::BeforeBuild:
    file: lib/Dist/Zilla/Plugin/Git/Remote/Check/BeforeBuild.pm
    version: v0.1.3
  Dist::Zilla::Plugin::Git::Remote::Update:
    file: lib/Dist/Zilla/Plugin/Git/Remote/Update.pm
    version: v0.1.3
  Dist::Zilla::Plugin::Git::Remote::Update::BeforeBuild:
    file: lib/Dist/Zilla/Plugin/Git/Remote/Update/BeforeBuild.pm
    version: v0.1.3
  Dist::Zilla::Role::Git::LocalRepository:
    file: lib/Dist/Zilla/Role/Git/LocalRepository.pm
    version: v0.1.3
  Dist::Zilla::Role::Git::LocalRepository::CurrentBranch:
    file: lib/Dist/Zilla/Role/Git/LocalRepository/CurrentBranch.pm
    version: v0.1.3
  Dist::Zilla::Role::Git::LocalRepository::LocalBranches:
    file: lib/Dist/Zilla/Role/Git/LocalRepository/LocalBranches.pm
    version: v0.1.3
  Dist::Zilla::Role::Git::Remote::Branch:
    file: lib/Dist/Zilla/Role/Git/Remote/Branch.pm
    version: v0.1.3
  Dist::Zilla::Role::Git::Remote::Check:
    file: lib/Dist/Zilla/Role/Git/Remote/Check.pm
    version: v0.1.3
  Dist::Zilla::Role::Git::Remote::Update:
    file: lib/Dist/Zilla/Role/Git/Remote/Update.pm
    version: v0.1.3
  Dist::Zilla::Role::Git::RemoteName:
    file: lib/Dist/Zilla/Role/Git/RemoteName.pm
    version: v0.1.3
  Dist::Zilla::Role::Git::RemoteNames:
    file: lib/Dist/Zilla/Role/Git/RemoteNames.pm
    version: v0.1.3
requires:
  Data::Dump: 0
  Dist::Zilla::Role::BeforeBuild: 0
  Dist::Zilla::Role::BeforeRelease: 0
  Dist::Zilla::Role::Plugin: 0
  Git::Wrapper: 0
  Moose: 0
  Moose::Role: 0
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/kentfredric/Dist-Zilla-Plugin-Git-Remote-Check/issues
  homepage: https://github.com/kentfredric/Dist-Zilla-Plugin-Git-Remote-Check
  repository: https://github.com/kentfredric/Dist-Zilla-Plugin-Git-Remote-Check.git
version: 0.1.3
x_BuiltWith:
  modules:
    Data::Dump: 1.22
    Dist::Zilla::Plugin::Author::KENTNL::MinimumPerl: 2.001000
    Dist::Zilla::Plugin::Authority: 1.006
    Dist::Zilla::Plugin::AutoPrereqs: 5.005
    Dist::Zilla::Plugin::CheckExtraTests: 0.015
    Dist::Zilla::Plugin::ConfirmRelease: 5.005
    Dist::Zilla::Plugin::EOLTests: 0.02
    Dist::Zilla::Plugin::Git::Check: 2.017
    Dist::Zilla::Plugin::Git::Commit: 2.017
    Dist::Zilla::Plugin::Git::CommitBuild: 2.017
    Dist::Zilla::Plugin::Git::GatherDir: 2.017
    Dist::Zilla::Plugin::Git::NextVersion: 2.017
    Dist::Zilla::Plugin::Git::Tag: 2.017
    Dist::Zilla::Plugin::GithubMeta: 0.42
    Dist::Zilla::Plugin::License: 5.005
    Dist::Zilla::Plugin::Manifest: 5.005
    Dist::Zilla::Plugin::ManifestSkip: 5.005
    Dist::Zilla::Plugin::MetaConfig: 5.005
    Dist::Zilla::Plugin::MetaData::BuiltWith: 0.04000000
    Dist::Zilla::Plugin::MetaJSON: 5.005
    Dist::Zilla::Plugin::MetaProvides::Package: 1.15000000
    Dist::Zilla::Plugin::MetaTests: 5.005
    Dist::Zilla::Plugin::MetaYAML: 5.005
    Dist::Zilla::Plugin::ModuleBuild: 5.005
    Dist::Zilla::Plugin::NextRelease: 5.005
    Dist::Zilla::Plugin::PkgVersion: 5.005
    Dist::Zilla::Plugin::PodCoverageTests: 5.005
    Dist::Zilla::Plugin::PodSyntaxTests: 5.005
    Dist::Zilla::Plugin::PodWeaver: 4.001
    Dist::Zilla::Plugin::Prereqs: 5.005
    Dist::Zilla::Plugin::Prereqs::MatchInstalled: 0.1.4
    Dist::Zilla::Plugin::PruneCruft: 5.005
    Dist::Zilla::Plugin::ReadmeAnyFromPod: 0.131500
    Dist::Zilla::Plugin::ReadmeFromPod: 0.21
    Dist::Zilla::Plugin::ReportVersions::Tiny: 1.10
    Dist::Zilla::Plugin::Test::CPAN::Changes: 0.008
    Dist::Zilla::Plugin::Test::Compile: 2.037
    Dist::Zilla::Plugin::Test::Kwalitee: 2.07
    Dist::Zilla::Plugin::Test::MinimumVersion: 2.000005
    Dist::Zilla::Plugin::Test::Perl::Critic: 2.112410
    Dist::Zilla::Plugin::TestRelease: 5.005
    Dist::Zilla::Plugin::Twitter: 0.023
    Dist::Zilla::Plugin::UploadToCPAN: 5.005
    Dist::Zilla::PluginBundle::Author::KENTNL: 2.001000
    Dist::Zilla::PluginBundle::Author::KENTNL::Lite: 1.7.2
    Dist::Zilla::Role::BeforeBuild: 5.005
    Dist::Zilla::Role::BeforeRelease: 5.005
    Dist::Zilla::Role::Plugin: 5.005
    File::Spec: 3.40
    Git::Wrapper: 0.030
    IO::Handle: 1.35
    IPC::Open3: 1.15
    Module::Build: 0.4008
    Moose: 2.1105
    Moose::Role: 2.1105
    Pod::Coverage::TrustPod: 0.100002
    Test::CPAN::Changes: 0.25
    Test::CPAN::Meta: 0.23
    Test::Kwalitee: 1.17
    Test::More: 1.001002
    Test::Pod: 1.48
    Test::Pod::Coverage: 1.08
    namespace::autoclean: 0.14
    strict: 1.08
    version: 0.9904
    warnings: 1.18
  perl:
    original: v5.19.3
    qv: 1
    version:
      - 5
      - 19
      - 3
  perl-config:
    gccversion: 4.7.2
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.11.6-gentoo x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  perl:
    version: 5.019003
  plugins:
    -
      class: Dist::Zilla::Plugin::Bootstrap::lib
      config:
        Dist::Zilla::Role::Bootstrap:
          distname: Dist-Zilla-Plugin-Git-Remote-Check
          fallback: 1
          try_built: 1
          try_built_method: mtime
      name: Bootstrap::lib
      version: 0.04000001
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::KENTNL/Git::NextVersion'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package: {}
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@Author::KENTNL/MetaProvides::Package'
      version: 1.15000000
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: 1
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: 0.04000000
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::KENTNL/Git::GatherDir'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::KENTNL/ReportVersions::Tiny'
      version: 1.10
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::KENTNL/Test::Kwalitee'
      version: 2.07
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::KENTNL/Test::Compile'
      version: 2.037
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::KENTNL/PruneCruft'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::KENTNL/PkgVersion'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
      name: '@Author::KENTNL/PodWeaver'
      version: 4.001
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::KENTNL/NextRelease'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/Prereqs/BundleDevelSuggests'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/Prereqs/BundleDevelRequires'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::Author::KENTNL::MinimumPerl
      name: '@Author::KENTNL/Author::KENTNL::MinimumPerl'
      version: 2.001000
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::KENTNL/ModuleBuild'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: 0.21
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Author::KENTNL/CheckExtraTests'
      version: 0.015
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::KENTNL/Git::Check'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_master'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::KENTNL/Git::Commit'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::KENTNL/Git::CommitBuild'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/Git::Tag/tag_release'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: 0.023
    -
      class: Dist::Zilla::Plugin::Prereqs::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::MatchInstalled:
          applyto:
            - build.requires
            - build.recommends
            - build.suggests
            - test.requires
            - test.recommends
            - test.suggests
            - runtime.requires
            - runtime.recommends
            - runtime.suggests
            - configure.requires
            - configure.recommends
            - configure.suggests
            - develop.requires
            - develop.recommends
            - develop.suggests
          applyto_phase:
            - build
            - test
            - runtime
            - configure
            - develop
          applyto_relation:
            - requires
            - recommends
            - suggests
          modules:
            - Module::Build
            - Test::More
            - Dist::Zilla::PluginBundle::Author::KENTNL
      name: '@Author::KENTNL/Prereqs::MatchInstalled'
      version: 0.1.4
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/::Role::BundleDeps'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::Git::Remote::Update
      name: Git::Remote::Update
      version: 0.1.3
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: Git::Remote::Check
      version: 0.1.3
    -
      class: Dist::Zilla::Plugin::Git::Remote::Update::BeforeBuild
      name: Git::Remote::Update::BeforeBuild
      version: 0.1.3
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check::BeforeBuild
      name: Git::Remote::Check::BeforeBuild
      version: 0.1.3
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 5.005
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.005
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.005
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.005
x_authority: cpan:KENTNL
